services:
  mongo1:
    image: mongo:6
    container_name: mongo1
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
    networks:
      - dbnetwork

  mongo2:
    image: mongo:6
    container_name: mongo2
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
    networks:
      - dbnetwork

  mongo3:
    image: mongo:6
    container_name: mongo3
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
    networks:
      - dbnetwork

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo1
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - dbnetwork

  backend:
    build: ./Backend
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
      - PORT=5000
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - dbnetwork
    ports:
      - "5000:5000"

networks:
  dbnetwork:

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: